### PR TITLE
Fixes endSeconds typo that wasn't allowing the video to be ended.

### PR DESCRIPTION
**Pull request by dalvtor**
I described a weird bug I was experimenting in this [issue](https://github.com/videojs/videojs-youtube/issues/520)

After reading the code, I saw a typo that was the cause of that behaviour. This PR fixes it.

### CODE REVIEW

**Comment by Dalvtor** [comment]
Sorry, changed the dist folder accidentally on first push, should be good now.

**Comment by nikwins** [comment]
Why wasn't this merged yet? This correctly fixes the issue

**Comment by DanielRuf** [comment]
Would be good to get this merged.

**Comment by gkatsev** [comment]
this LGTM. I think I just forgot about it. Not sure how I even ended up having it `endEnd` in the first place.

**Comment by gkatsev** [comment]
This is released in version 2.6.1, thanks for everyone's patience.

**Pull request merged**
