### PR TITLE
Fix massive performance issue with large videos

### PR DESCRIPTION
**Pull request by jbourassa**
Time range length property (returned by`buffered` and `seekable`)
should represent the number of time ranges our start and end
function will respond to[1]. In this case, we only know the
percentage loaded so we're assuming that it starts at the beginning.

I think that logic is flawed but that may be the best possible solution
given what the YouTube API returns.

In any event, using the duration as the `length` makes VideoJS loop
`length` times to call `start` and `end`. This happens a few times
per second, making the video barely usable for very long videos.

[1] If I understand correctly.

### CODE REVIEW

**Comment by gkatsev** [comment]
This makes sense to me. We do actually have an exposed ["createTimeRanges"](https://github.com/videojs/video.js/blob/master/src/js/video.js#L524) method on videojs (API doc [here](https://github.com/videojs/video.js/blob/master/src/js/utils/time-ranges.js#L115-L126)) that we should probably start using instead of doing it manually.

**Comment by gkatsev** [comment]
I opened an issue for the API usage. https://github.com/videojs/videojs-youtube/issues/417

**Comment by gkatsev** [comment]
In 2.2.0, thanks!

**Comment by onigetoc** [comment]
i'm playing Livestream Youtube video and this error is alway appearing and slow down my computer.
ex: https://www.youtube.com/watch?v=yIYLbf-qHfY

**Comment by jbourassa** [comment]
@onigetoc 

>Youtube video and this error is alway appearing and slow down my computer.

Which error is _this error_?

**Comment by onigetoc** [comment]
the same principal error in this post; Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. #416

**Comment by jbourassa** [comment]
@onigetoc ^ Well I'm not sure if it's related, but it may be. I suggest you open up a new issue with a demo that reproduces the issue so someone can look into it, since this PR has been merged.

**Pull request merged**
