### PR TITLE
Enable playback rate button

### PR DESCRIPTION
**Pull request by Marco129**
Related to #366
The existing playbackRate and setPlaybackRate function work fine. Just needed to enable featuresPlaybackRate and fix the position that trigger the event.

### CODE REVIEW

**Comment by misteroneill** [comment]
I think this would have to take into account that not all YouTube players support variable playback rates.

**Comment by gkatsev** [comment]
Yeah, I wonder if we can detect/ask youtube for whether they support playback rate and only then enable playback rate.

**Comment by Marco129** [comment]
Yes, we can detect it using getAvailablePlaybackRates.
https://developers.google.com/youtube/iframe_api_reference#getAvailablePlaybackRates

Is there any method to set Youtube.prototype.featuresPlaybackRate after YouTube API is ready?

**Comment by gkatsev** [comment]
I'm not sure we really support the changing of features after a tech is ready. Though, we could also say that the youtube tech isn't ready until the youtube api has loaded (if it isn't already) in which case we can defer setting the feature until then.

**Comment by gkatsev** [comment]
Finally looked into this. I think that if we change `featuresPlaybackRate` to true above [`triggerReady`](https://github.com/videojs/videojs-youtube/blob/015255f78bdc05b566b3deb56f58fe4009ebac42/src/Youtube.js#L239-L240), we will be able to turn it on dynamically. We can add something like:
```js
      var playbackRates = this.ytPlayer.getAvailablePlaybackRates();
      if (playbackRates.length > 1) {
        this.featuresPlaybackRate = true;
      }
```
The only downside is that it would still require the user to configure the videojs player to provide playbackrates (otherwise the menubutton isn't shown). We could consider updating videojs to be able to ask the tech for the playback rates.

**Comment by narration-sd** [comment]
Asking the tech for the rates seems good, provided there’s good behavior if it can’t get them…

 

Like to hear adaptive software thinking like this – bound to be helpful when you are dealing with YouTube/BigG and their penchant for just altering things…

**Comment by Marco129** [comment]
It is a good idea to support getting playback rates from tech.
I updated the code to determine support of playbackRate dynamically, thanks @gkatsev !

**Comment by gkatsev** [comment]
I opened up an issue against videojs wrt this: https://github.com/videojs/video.js/issues/3943

**Comment by gkatsev** [comment]
Out as 2.3.0, thanks @Marco129

**Pull request merged**
